[package]
name = "glium_macros"
version = "0.0.2"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[lib]
name = "glium_macros"
path = "src/lib.rs"
plugin = true

[dependencies.glslang]
git = "https://github.com/tomaka/glslang-rs"
optional = true

[dev-dependencies.glium]
default-features = false
version = "*"
path = ".."
